// The capture pointer: which capture run the build reads.
// Relative to the repo root. A record, not a switch: this names the run the
// served tree came from, and no live run exists to point it at (ADR 0004). The
// build still accepts `--run <dir>` for a hypothetical fresh capture.
//
// `2026-09-12` is the snapshot: a full capture of the live site, 1,200/1,200
// pages saved, 0 failed, taken with the corrected SingleFile flags that keep the
// hidden subtrees and state CSS
// (`--remove-hidden-elements=false --remove-unused-styles=false`), the flags
// recorded in ADR 0004. It is the run the phase-gate signoff covers.
//
// **The capture itself is gone, and that is now the design.** The run lived
// under `.scratch/` — 34.5 GB of captured HTML, gitignored because heavy HTML
// never belonged in git — and the whole scratch tree was scrapped when the
// effort closed (2026-09-13). The Recreation is a **frozen snapshot** of
// the live site on that date, not a mirror that follows it: the refresh workflow
// (re-inventory → diff → scoped re-capture) was retired when the snapshot was
// declared final (ADR 0004). So this pointer names the run the served tree came
// from, `npm run pipeline` cannot run again, and `served/` is the artifact. The
// build stays as the snapshot's recipe — its tests drive it over fixtures — and
// the serving check does not need captures at all (`CAPTURE_LIST` below).
export const CAPTURE_RUN = 'research/flocksafety/2026-09-12';

// The page listing the 2026-09-12 run recorded, kept after the captures were
// scrapped. The serving check's count invariant (served + dropped = the pages
// the build was asked for) compares the built tree against the set it was built
// from — a record, which is exactly what a frozen snapshot can no longer supply
// any other way. Copy of
// `.scratch/flock-parody/research/flocksafety/2026-09-12/capture-list.txt`, taken
// before the deletion and never regenerated by the build.
export const CAPTURE_LIST = 'regression/capture-list-2026-09-12.txt';

// Wistia medias that are gone upstream, so there is nothing to mimic: Wistia
// answers their media JSON with `{"error":true}` (deleted or made private in
// the account), which means the embed is broken on the live site too. The embed
// pass (ADR 0002) leaves these slots in their captured end-state instead of
// pointing a player at a media that cannot play. **Frozen with the snapshot**
// (ADR 0004): the list was measured once, by probing each media upstream while
// the refresh workflow still existed, and the probe is gone — no tool re-derives
// it, and nothing here tries to follow the live site.
// The list is only as complete as the slot detection that fed it: the retired
// live-site inventory read URLs, so when the embed pass first turned an
// attribute-form slot (`<wistia-player media-id=tthkbjay3c>`) into a live embed
// URL, that media was already live before the inventory ever saw it, the probe
// found it dead, and this list came up one entry short. Ticket 17 added the
// attribute-form detection (it lives on in `pipeline/video-inventory.mjs`),
// which is why that id is here at all.
export const DEAD_VIDEO_IDS = ['77o31nkq0o', 'gayegdwaii', 'imr6vzeawt', 'ueo7k59ryn', 'tthkbjay3c'];

// Legibility patches: page-scoped CSS the Recreation injects inline as a marked
// `<style>` (build pass 12) to make text the Capture left unreadable legible.
// On `/safe-cities` the page's own `.t-subhead-1{color:#304833}` rule puts dark
// body copy on the dark `#061602` screen sections. The override is scoped to
// those sections, so the same classes on the white FAQ accordion stay dark.
// (The section's scrub-word headings are a separate case: their dark captured
// from-colour is normalized to the light end-state and animated by the scroll
// layer — ticket 21.) Keyed by page path; a page with no entry is not patched.
// This is a deliberate divergence from the live bytes (ticket 12 human review)
// and is recorded in the signoff.
export const LEGIBILITY_PATCHES = {
  '/safe-cities': `
.l-section--full.bg-screen.scroller .t-subhead-1 { color: #fff; }
`,
};

// Scaffold/test pages: captured 200 pages that are internal Webflow test
// scaffolding, not site content, and are dropped from serving entirely
// (spec, "Serving and links"). The Recreation serves the live inventory minus
// this list; every dropped path 404s.
//
// The list is explicit (not a runtime heuristic) so it is auditable and a
// stale entry fails the build loudly. Membership rule: the page's slug marks
// it as a test scaffold, AND no other served page links to it (verified
// corpus-wide: dropping these introduces no Recreation-introduced dead link).
// Real content pages whose slugs merely contain a suggestive word are NOT
// here — e.g. /business-template ("Business Funding Letter Template", a gated
// resource), /book-a-demo-layout ("Ready When You Are"), /fb-click-id and
// /privacy-ethics-copy all carry real captured body content and stay served.
export const DROPPED_PAGES = [
  '/book-a-demo-form-test',
  '/book-a-demo-short-form-test',
  '/book-a-demo-test',
  '/email-exclusions-test',
  '/form-test',
  '/webinar/this-is-a-test',
  '/webinar/webinar-test-evens-page',
  '/webinar/webinar-test-evens-page-copy',
  '/webinar/webinar-test-evens-page-copy-2',
  '/webinar/webinar-test-evens-page-copy-3',
  '/webinar/webinar-test-evens-page-copy-4',
  '/webinar/webinar-test-evens-page-copy-5',
  '/webinar/webinar-test-evens-page-copy-6',
  '/webinar/webinar-test-evens-page-copy-7',
  '/webinar/webinar-test-evens-page-copy-8',
  '/webinar/webinar-test-evens-page-copy-9',
  '/webinar/webinar-test-evens-page-copy-10',
  '/webinar/webinar-test-evens-page-copy-11',
  '/webinar/webinar-test-evens-page-past',
];
