// The frozen inputs the serving check still reads.
//
// There was a build here. It turned a 34.5 GB capture run into the served tree,
// and it cannot run again: the run lived under `.scratch/` (gitignored, because
// heavy HTML never belonged in git) and was scrapped when the effort closed
// (2026-09-13). The Recreation is a **frozen snapshot** of the live site on
// 2026-09-12, not a mirror that follows it — `served/` is committed and is the
// artifact, and nothing here can regenerate it.
//
// What survives is what checking that artifact needs: the page listing behind
// the serving check's count invariant, and the scaffold pages it must 404.
//
// SPDX-License-Identifier: CC0-1.0

// The page listing the 2026-09-12 run recorded, kept after the captures were
// scrapped. The serving check's count invariant (served + dropped = the pages
// the build was asked for) compares the tree against the set it was built from —
// a record, which is exactly what a frozen snapshot can no longer supply any
// other way. Copy of
// `.scratch/flock-parody/research/flocksafety/2026-09-12/capture-list.txt`, taken
// before the deletion and never regenerated by the build.
export const CAPTURE_LIST = 'regression/capture-list-2026-09-12.txt';

// Legibility patches: page-scoped CSS the Recreation injects inline as a marked
// `<style>` so that text the Capture left unreadable is readable. On
// `/safe-cities` the Capture froze the GSAP scrub labels at their dark start
// colour — the live page paints them the section's light content colour — and
// the page's own `.t-subhead-1{color:#304833}` rule puts dark body copy on the
// `#061602` screen sections. The override is scoped to those sections, so the
// same classes on the white FAQ accordion stay dark. Keyed by page path; a page
// with no entry is simply not patched. This is a deliberate divergence from the
// live bytes, recorded in the ticket-12 signoff.
//
// It is also the source of the `legibility` marked member: the tree ships the
// bytes, so the map that produced them is what a check compares against. Kept
// verbatim when the build half was retired — the map outlives the pass.
/** @type {Record<string, string>} */
export const LEGIBILITY_PATCHES = {
  '/safe-cities': `
.l-section--full.bg-screen.scroller .t-subhead-1 { color: #fff; }
`,
};

// Scaffold/test pages: captured 200 pages that are internal Webflow test
// scaffolding, not site content, and are dropped from serving entirely. The
// Recreation serves the live inventory minus this list; every dropped path 404s.
//
// The list is explicit (not a runtime heuristic) so it is auditable. Membership
// rule: the page's slug marks it as a test scaffold, AND no other served page
// links to it (verified corpus-wide: dropping these introduces no
// Recreation-introduced dead link). Real content pages whose slugs merely
// contain a suggestive word are NOT here — e.g. /business-template ("Business
// Funding Letter Template", a gated resource), /book-a-demo-layout ("Ready When
// You Are"), /fb-click-id and /privacy-ethics-copy all carry real captured body
// content and stay served.
export const DROPPED_PAGES = [
  '/book-a-demo-form-test',
  '/book-a-demo-short-form-test',
  '/book-a-demo-test',
  '/email-exclusions-test',
  '/form-test',
  '/webinar/this-is-a-test',
  '/webinar/webinar-test-evens-page',
  '/webinar/webinar-test-evens-page-copy',
  '/webinar/webinar-test-evens-page-copy-2',
  '/webinar/webinar-test-evens-page-copy-3',
  '/webinar/webinar-test-evens-page-copy-4',
  '/webinar/webinar-test-evens-page-copy-5',
  '/webinar/webinar-test-evens-page-copy-6',
  '/webinar/webinar-test-evens-page-copy-7',
  '/webinar/webinar-test-evens-page-copy-8',
  '/webinar/webinar-test-evens-page-copy-9',
  '/webinar/webinar-test-evens-page-copy-10',
  '/webinar/webinar-test-evens-page-copy-11',
  '/webinar/webinar-test-evens-page-past',
];
