// The catch-all serving route: the Recreation answers original site paths
// from the build's served tree. GET /a/b → served/a/b.html, or served/a/b/
// index.html; anything else is a 404 — reproducing the live site's observed
// behavior IS the fidelity bar. Pages are read from disk per request (the
// served tree is a build artifact, regenerated by `npm run pipeline`; ticket
// 07 adds the legacy-redirect manifest and whole-site scale).
//
// SERVED_DIR overrides the tree location (tests point it at a fixture build);
// it defaults to <cwd>/served.
import { readFile } from 'node:fs/promises';
import path from 'node:path';

export const dynamic = 'force-dynamic';

function servedDir(): string {
  return process.env.SERVED_DIR ?? path.join(process.cwd(), 'served');
}

function candidateFiles(segs: string[]): string[] {
  if (segs.length === 0) return [path.join(servedDir(), 'index.html')];
  const rel = segs.join('/');
  return [path.join(servedDir(), `${rel}.html`), path.join(servedDir(), rel, 'index.html')];
}

function notFound(): Response {
  return new Response('Not found', {
    status: 404,
    headers: { 'content-type': 'text/plain; charset=utf-8', 'cache-control': 'no-store' },
  });
}

export async function GET(_req: Request, { params }: { params: Promise<{ path?: string[] }> }) {
  const { path: segs = [] } = await params;
  if (segs.some((s) => s === '.' || s === '..')) {
    return notFound();
  }
  for (const file of candidateFiles(segs)) {
    try {
      const html = await readFile(file, 'utf8');
      return new Response(html, {
        status: 200,
        headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' },
      });
    } catch {
      // try the next candidate
    }
  }
  return notFound();
}
