// The catch-all serving route: the Recreation answers original site paths
// from the build's served tree. GET /a/b → served/a/b.html, or served/a/b/
// index.html; a miss consults the build's redirect table (ticket 07) and
// answers the legacy stubs' permanent redirect; anything else is a 404 —
// reproducing the live site's observed behavior IS the fidelity bar (dead
// collection roots and dropped scaffold/test pages 404 here). Pages are read
// from disk per request (the served tree is a build artifact, regenerated by
// `npm run pipeline`).
//
// SERVED_DIR overrides the tree location (tests point it at a fixture build);
// it defaults to <cwd>/served — see lib/serving.ts.
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { notFound, permanentRedirect, redirectFor, servedDir } from '@/lib/serving';

export const dynamic = 'force-dynamic';

export async function GET(_req: Request, { params }: { params: Promise<{ path?: string[] }> }) {
  const { path: segs = [] } = await params;
  const rel = segs.join('/');
  const candidates = (segs.length === 0 ? [path.join(servedDir(), 'index.html')] : [path.join(servedDir(), `${rel}.html`), path.join(servedDir(), rel, 'index.html')])
    .map((f) => path.resolve(f));
  // Construction-grade traversal guard: resolve the candidate and require it
  // to stay inside the served tree (compound/encoded segments included).
  if (candidates.some((f) => !f.startsWith(path.resolve(servedDir()) + path.sep))) {
    return notFound();
  }
  const html = await readServed(candidates);
  if (html !== null) {
    return new Response(html, {
      status: 200,
      headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' },
    });
  }
  const target = await redirectFor('/' + rel);
  if (target !== null) return permanentRedirect(target);
  return notFound();
}

/** The first candidate that exists, or null — served pages are plain files. */
async function readServed(candidates: string[]): Promise<string | null> {
  for (const file of candidates) {
    try {
      return await readFile(file, 'utf8');
    } catch {
      // try the next candidate
    }
  }
  return null;
}
