// The catch-all serving route: the Recreation answers original site paths
// from the build's served tree. GET /a/b → served/a/b.html, or served/a/b/
// index.html; anything else is a 404 — reproducing the live site's observed
// behavior IS the fidelity bar. Pages are read from disk per request (the
// served tree is a build artifact, regenerated by `npm run pipeline`; ticket
// 07 adds the legacy-redirect manifest and whole-site scale).
//
// SERVED_DIR overrides the tree location (tests point it at a fixture build);
// it defaults to <cwd>/served — see lib/serving.ts.
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { notFound, servedDir } from '@/lib/serving';

export const dynamic = 'force-dynamic';

export async function GET(_req: Request, { params }: { params: Promise<{ path?: string[] }> }) {
  const { path: segs = [] } = await params;
  if (segs.length === 0) {
    return serve([path.join(servedDir(), 'index.html')]);
  }
  // Construction-grade traversal guard: resolve the candidate and require it
  // to stay inside the served tree (compound/encoded segments included).
  const rel = segs.join('/');
  const candidates = [path.join(servedDir(), `${rel}.html`), path.join(servedDir(), rel, 'index.html')]
    .map((f) => path.resolve(f));
  if (candidates.some((f) => !f.startsWith(path.resolve(servedDir()) + path.sep))) {
    return notFound();
  }
  return serve(candidates);
}

async function serve(candidates: string[]): Promise<Response> {
  for (const file of candidates) {
    try {
      const html = await readFile(file, 'utf8');
      return new Response(html, {
        status: 200,
        headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' },
      });
    } catch {
      // try the next candidate
    }
  }
  return notFound();
}
